name       : pam-krb5
version    : 4.8
release    : 1
source     :
    - https://archives.eyrie.org/software/kerberos/pam-krb5-4.8.tar.xz : cbb59f6f72ad6207c8376b14af89badadd62fbfc7f661ca779e7afa4434457e2
license    : BSD-3-Clause
component  : security
summary    : PAM module for MIT Kerberos
description: |
    A Kerberos PAM module build against the MIT Kerberos libraries.
    It supports authenticating against a Kerberos KDC,
    obtaining tickets and populating an initial ticket cache,
    authorizing users via a ~/.k5login file,
    and changing Kerberos passwords.
builddeps  :
    - pkgconfig(krb5)
    - pkgconfig(com_err)
rundeps    :
    - kerberos
setup      : |
    %configure --enable-reduced-depends --libdir=/lib64
build      : |
    %make
install    : |
    %make_install
