name       : pam-krb5
version    : '4.9'
release    : 3
source     :
    - https://archives.eyrie.org/software/kerberos/pam-krb5-4.9.tar.xz : 915445fd492c8afde497090760035043edba44660d1c53ce8cb6477b0f80b6f3
license    : BSD-3-Clause
component  : security
summary    : PAM module for MIT Kerberos
description: |
    A Kerberos PAM module build against the MIT Kerberos libraries.
    It supports authenticating against a Kerberos KDC,
    obtaining tickets and populating an initial ticket cache,
    authorizing users via a ~/.k5login file,
    and changing Kerberos passwords.
builddeps  :
    - pkgconfig(krb5)
    - pkgconfig(com_err)
rundeps    :
    - kerberos
setup      : |
    %configure --enable-reduced-depends --libdir=/lib64
build      : |
    %make
install    : |
    %make_install
